version: '3.8'

services:
  s1panel:
    container_name: s1panel
    build:
      context: .
      dockerfile: Dockerfile
    image: s1panel-service
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /sys/class/net:/sys/class/net:ro
    devices:
      - /dev/ttyUSB0
      - /dev/bus/usb
